# Generated by Django 4.2.3 on 2023-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='account_images'),
        ),
    ]
