# Generated by Django 4.2.3 on 2023-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
