# Generated by Django 4.2.3 on 2023-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
    ]
