# Generated by Django 4.2.3 on 2023-07-14 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='Создатель тестов'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('test_creator', 'Составитель тестов'), ('test_taker', 'Студент'), ('test_grader', 'Преподаватель')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
