# Generated by Django 4.2.3 on 2023-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='', max_length=250, verbose_name='Правильный ответ'),
        ),
    ]
